### ISSUE TITLE
 When a excel xlsx file has more than one sheet, how to choose the certain sheet?

### ISSUE THREAD

**Issue by gadmyth** [multiprocessio/dsq#27]
If you don't choose the certain sheet, it'll throw DSError
`DSError {
  "name": "Error",
  "message": "invalid character ',' looking for beginning of object key string",
  "stack": "goroutine`

So, if you delete the other default created sheet2 and sheet3,  and remain the only sheet1, dsq will works fine.

**Comment by eatonphil** [comment]
Yes that's right it doesn't work at the moment. The README mentions.

One thing you could do is something like:

```
$ dsq $excelfile | jq '$sheetname' | dsq 'select * from {}'
```

Because dsq doesn't yet support specifying a path within an object.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/3925912/156903331-ae6417c6-9ab1-4827-bcac-2653556c0cb7.png">

**Comment by eatonphil** [comment]
Separately, I am working on adding support for specifying a path. It might be available in a release next week.

**Comment by eatonphil** [comment]
This is now supported in `dsq` in version 0.6.0.

See the updated README for details.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/3925912/157294708-d27a66bc-7b9d-4996-9244-d5267a04d541.png">
