### ISSUE TITLE
Support streaming JQ objects

### ISSUE THREAD

**Issue by singpolyma** [multiprocessio/dsq#9]
Like `jq` does, support streaming JQ objects with no required newline or other separator.

**Comment by eatonphil** [comment]
Great question but I think that that is not going to be possible because of the architecture. Unlike JQ each row is not acted on individually. Instead rows get put into SQLite and then you can do arbitrary queries on the result.

For example because it's not just filtering you can do stuff like `SELECT COUNT(1), name FROM users GROUP BY name ORDER BY COUNT(1) DESC` which wouldn't be possible in something like `jq` that is just doing row-wise filtering/mapping/reducing.

I do agree it would be a nice feature if the point of `dsq` was only to support `SELECT $fields WHERE $filter` but since it does more than that I'm not sure this will ever be possible. I'll still keep thinking about it though.

**Comment by eatonphil** [comment]
Ohh I see you don't mean that the output has to be streamed too you're just talking about a new input format. Is there a name for this format (file extension and mimetype) so that I can use the right convention?

**Comment by eatonphil** [comment]
Looks like wikipedia calls it "concatenated JSON": https://en.wikipedia.org/wiki/JSON_streaming. So I guess I'll go with `.cjson` and `application/json-concat` for the mimetype?

**Comment by eatonphil** [comment]
If someone else wants to hack this in before I get to it, just add a new mimetype and transformer here: https://github.com/multiprocessio/datastation/blob/main/runner/http.go#L154. Then once that is merged in datastation this repo can be updated to the latest hash and will support it.

**Comment by eatonphil** [comment]
I'm working on this now https://github.com/multiprocessio/datastation/pull/162.

**Comment by eatonphil** [comment]
This is released now. Install 0.3.0 and it will support .cjson files or with the mimetype `application/jsonconcat`
